title: Mary Acklin
email: acklin.mary@gmail.com
description: >-
  Online portfolio and contact for Mary Acklin, professional writer and content strategist.
baseurl: ""
url: "http://www.maryacklin.com/"
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
